// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxbCBAC2lRRV4IvEqjrEd-pJMh_-14LQc',
    appId: '1:609833610754:web:1089ec683be5d07658411b',
    messagingSenderId: '609833610754',
    projectId: 'minimal-social-app-195dd',
    authDomain: 'minimal-social-app-195dd.firebaseapp.com',
    storageBucket: 'minimal-social-app-195dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmWE7EGbmv0eM9WPHSaZPzAWo0HCbWDg',
    appId: '1:609833610754:android:8454c7fafddf305758411b',
    messagingSenderId: '609833610754',
    projectId: 'minimal-social-app-195dd',
    storageBucket: 'minimal-social-app-195dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi7zkVTYlEDsGZErw6bJdXjCV19myTCi8',
    appId: '1:609833610754:ios:e1142311a0c8972a58411b',
    messagingSenderId: '609833610754',
    projectId: 'minimal-social-app-195dd',
    storageBucket: 'minimal-social-app-195dd.appspot.com',
    iosBundleId: 'com.example.minimal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi7zkVTYlEDsGZErw6bJdXjCV19myTCi8',
    appId: '1:609833610754:ios:2e54f25e5f1b349f58411b',
    messagingSenderId: '609833610754',
    projectId: 'minimal-social-app-195dd',
    storageBucket: 'minimal-social-app-195dd.appspot.com',
    iosBundleId: 'com.example.minimal.RunnerTests',
  );
}
